### ISSUE TITLE
Toggle needs to run twice to turn off

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/do-not-disturb#1]
Followed the install steps on https://github.com/sindresorhus/do-not-disturb-cli

When I run `dnd` (alias of `do-not-disturb toggle`) it toggles successfully, but when I run it several times one after the other it has some problems.

It always enables the do not disturb mode, but it turns it off only after the 2nd time I run the command while the DND is on.

I reproduce this behaviour consistently every time.

**Comment by sindresorhus** [comment]
Yes, I noticed this too after publishing. I was gonna open an issue about this, but got busy.

The problem is https://github.com/sindresorhus/do-not-disturb/blob/770469cd288888588b394e86c37921a7d1a5b627/Sources/do-not-disturb/DoNotDisturb.swift#L31, it returns incorrect results, causing toggle to use the wrong method. I'll have to look deeper into this.
